server:
  image: "aerospike/aerospike-server:latest"
  ports:
    - "3000:3000"

client:
  build: ./client
  links:
    - server

bench-ruby:
  build: ./aerospike-client-ruby
  links:
    - server

bench-java:
  build: ./aerospike-client-java
  links:
    - server